/**
 * manifest.json (schemaVersion 2) — the unified update contract.
 *
 * Published per-app on the bookforge repo's `catalog-data` branch and served via
 * raw.githubusercontent.com, polled by the launcher (and the running app) on startup. It is
 * the single source of truth for every
 * updatable thing, across three tiers + the existing catalog content:
 *
 *   - launcher   the .app / .exe itself (rare; updated by manual re-download)
 *   - code       "BookForge proper" — the pure-JS code bundle in userData (frequent, auto)
 *   - components binaries/models the app downloads (ffmpeg, yt-dlp, cuda, voices, language packs)
 *   - voices / languages  the existing catalog content (generated by the indexer), folded in here
 *
 * Trust model: there is NO code signing. Every downloadable artifact carries a `sha256` that
 * the client verifies after download — that hash, served over HTTPS from a host we control, is
 * the integrity anchor in place of a signature.
 *
 * Hosting: the manifest lives on the bookforge repo's `catalog-data` branch (orchestration),
 * served via raw.githubusercontent.com; large artifacts live on GitHub Releases. Either way
 * the client only follows `url` + verifies `sha256`.
 *
 * This file is the canonical TypeScript shape. The server (catalog/release indexer) and the
 * launcher each mirror it; keep them in sync when bumping `schemaVersion`.
 */

import type { CatalogVoice, CatalogLanguage } from '../components/catalog-types';

export const MANIFEST_SCHEMA_VERSION = 2 as const;

/** Platform+arch key used to select the right artifact. `${process.platform}-${process.arch}`. */
export type PlatformArch =
  | 'darwin-arm64'
  | 'darwin-x64'
  | 'win32-x64'
  | 'linux-x64'
  // Allow forward-compatible keys without a type break.
  | (string & {});

/**
 * A single downloadable file. `bytes` is advisory (progress UI / disk pre-check); `sha256` is
 * mandatory and verified after download before the artifact is trusted.
 */
export interface Artifact {
  url: string;
  sha256: string;
  bytes: number;
}

/**
 * A semver range string (e.g. ">=1.0.0", "^0.3.0"). Compatibility gates are expressed as ranges
 * so a release can require "this or newer" without pinning an exact version.
 */
export type SemverRange = string;

/**
 * Tier 3 — the launcher (the persistent .app/.exe in /Applications or %LocalAppData%).
 * Platform-specific (it bundles the Electron runtime + native node_modules). Updated rarely and
 * by manual re-download, since replacing it is the one step that isn't signing-free-automatic.
 */
export interface LauncherRelease {
  version: string;
  platforms: Partial<Record<PlatformArch, Artifact>>;
}

/**
 * Tier 1 — "BookForge proper": the code bundle (compiled electron/ + Angular renderer).
 *
 * Platform-AGNOSTIC: it ships pure JS only (no node_modules, no native .node), so a single
 * artifact serves every platform. Native deps resolve from the launcher at runtime — which is
 * also why `minLauncher` exists: it gates the rare case where new code needs a newer launcher
 * (e.g. a newer better-sqlite3 JS API or Electron). A code-only update can never hit a native
 * ABI mismatch, so this is the common, frequent, fully-automatic update path.
 */
export interface CodeRelease {
  version: string;
  url: string;
  sha256: string;
  bytes: number;
  /** Minimum launcher version this code bundle is compatible with. */
  minLauncher: SemverRange;
}

/**
 * Tier 2 — a managed component the app downloads (ffmpeg, yt-dlp, cuda pack, an env tarball…).
 *
 * Either platform-agnostic (`artifact` set — e.g. a model) or platform-specific (`platforms`
 * set — e.g. a binary). Exactly one of the two should be present.
 *
 * `requiresApp` is the coupling gate that makes the yt-dlp use case work: a new binary that the
 * app's code doesn't yet know how to drive is withheld until the code bundle is new enough.
 */
export interface ComponentRelease {
  /** Stable component id (matches the component-manager registry, e.g. 'ffmpeg', 'yt-dlp'). */
  id: string;
  version: string;
  /** Executable path within the extracted artifact. Defaults to the id (id+'.exe' on Windows).
   *  Set when the binary lives in a subdir, e.g. 'bin/ffmpeg'. */
  entry?: string;
  /** Platform-agnostic artifact (models, etc.). Mutually exclusive with `platforms`. */
  artifact?: Artifact;
  /** Per-platform artifacts (native binaries). Mutually exclusive with `artifact`. */
  platforms?: Partial<Record<PlatformArch, Artifact>>;
  /** Withhold this release until the installed code bundle satisfies this range. */
  requiresApp?: SemverRange;
  /** Withhold until the installed launcher satisfies this range (rare; e.g. ABI-bound packs). */
  minLauncher?: SemverRange;
}

/**
 * The bundled "starter library" — a complete, finished public-domain sample project that the app
 * downloads ONCE into a brand-new, EMPTY library on first run (so a fresh user has something real
 * to look at). Content, not code: downloaded + sha256-verified like a component, but never part of
 * the auto-update tiers and never re-fetched once a library has any projects. The archive is rooted
 * at the library root, so it extracts straight into {library}/ as projects/<slug>/ + media/<cover>.
 */
export interface StarterRelease {
  /** The project folder name inside projects/ (for "already present?" reporting). */
  slug: string;
  url: string;
  sha256: string;
  bytes: number;
  /** Human label, e.g. 'the-mysterious-stranger'. */
  name?: string;
}

/**
 * The full manifest. A superset of the old CatalogData: it keeps `voices`/`languages` (still
 * generated by the indexer) and adds the three update tiers. `app` is the per-app namespace so
 * one server can serve BookForge and (later) the briefcase app from sibling manifests.
 */
export interface UpdateManifest {
  schemaVersion: typeof MANIFEST_SCHEMA_VERSION;
  /** Per-app namespace, e.g. 'bookforge'. Matches the URL path segment. */
  app: string;
  generatedAt: string;
  generator: string;

  launcher: LauncherRelease;
  code: CodeRelease;
  components: ComponentRelease[];
  /** Optional one-time starter library seeded into an empty library on first run. */
  starter?: StarterRelease;

  // --- Carried over from CatalogData (unchanged, still produced by the indexer) ---
  sources?: { voices: string; languages: string };
  counts?: { voices: number; languages: number };
  voices: CatalogVoice[];
  languages: CatalogLanguage[];
}

/**
 * Pick the artifact for the current platform from a release that may be platform-specific or
 * platform-agnostic. Returns null when no artifact matches (caller treats as "not available
 * for this platform").
 */
export function selectArtifact(
  release: { artifact?: Artifact; platforms?: Partial<Record<PlatformArch, Artifact>> },
  platformArch: PlatformArch
): Artifact | null {
  if (release.artifact) return release.artifact;
  if (release.platforms) return release.platforms[platformArch] ?? null;
  return null;
}

/** Convenience: build the current platform key the same way everywhere. */
export function currentPlatformArch(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch
): PlatformArch {
  return `${platform}-${arch}`;
}
