/**
 * Within-batch progress for the Orpheus MLX audiobook path.
 *
 * On Mac the Orpheus engine renders a full-width static batch (~96 rows) in ONE
 * BatchGenerator decode that runs 5-7 minutes. Every sentence FILE in that batch
 * lands at the very end, and so does every completion line the worker prints —
 * so a bar counting completions alone is frozen for the whole decode and then
 * jumps 96 chunks at once. The only signal that exists inside the decode is the
 * engine's throttled heartbeat line (orpheus.py `_convert_mlx_batch`):
 *
 *   [ORPHEUS] MLX batch generating: 95 rows, ~1259 tokens (step 1260/3400), 12/95 rows done, batch 1/2
 *
 * Rows RETIRE individually inside that decode (each hits EOS on its own step),
 * and `12/95 rows done` is the engine counting them. This module turns the line
 * into two things:
 *
 *  - `fraction`, a monotone 0-1 for a secondary bar (no longer drawn in the
 *    desktop UI — see `rowsRetiredInCall` — but still on the wire);
 *  - `rowsRetiredInCall`, the rows retired so far across the WHOLE engine call,
 *    which the bridge folds into the chunk count so the Mac's chunk bar ticks
 *    off rows as they exit the batch, the way the PC's does (Owen, 2026-09-11).
 *
 * It is deliberately dependency-free (no electron, no session types) so the
 * parsing/carry-over rules can be exercised directly.
 *
 * BACKWARD COMPATIBILITY: the older engine printed only
 *   [ORPHEUS] MLX batch generating: 95 rows, ~1259 tokens (step 1260)
 * — the prefix is byte-identical, so every field after the token count is
 * optional here. An old fork against this build still parses (token-only
 * progress, no row count); a new fork against an old build still matched the old
 * bridge regex, which stopped at "tokens".
 */

/** Raw fields read off one heartbeat line. Absent fields were not printed. */
export interface MlxHeartbeat {
  /** Rows (chunks) in this batch. */
  rowsTotal: number;
  /** Tokens generated by the deepest row so far (the engine's `~N tokens`). */
  maxTokens: number;
  /** Decode steps taken (1 token per live row per step). */
  step?: number;
  /** The batch's max_tokens bound — min(MLX_MAX_TOKENS, per-batch budget). */
  tokenCap?: number;
  /** Rows retired so far (finish_reason 'stop' or the 'length' cap). */
  rowsDone?: number;
  /** 1-based batch ordinal within the engine call, and the call's batch count. */
  batchNo?: number;
  batchCount?: number;
}

/** What the bridge publishes and the UI draws. */
export interface ActiveBatchProgress {
  rowsTotal: number;
  /**
   * Rows retired, when the engine reports it (0 until the first row hits EOS —
   * that is honest, not missing). Absent against an older engine that only
   * printed the token count.
   */
  rowsDone?: number;
  /** Deepest row's token count (what the engine calls `~N tokens`). */
  tokenStep: number;
  /** The batch's token-depth bound, when the engine reported one. */
  tokenCap?: number;
  /**
   * 0-1, monotone within a batch, reset at a batch boundary. ABSENT when the
   * heartbeat carries no basis for one (an older engine printing neither a row
   * count nor a token cap) — the UI then shows the batch as text with no bar,
   * rather than a bar pinned at zero that reads as a stall.
   */
  fraction?: number;
  batchNo?: number;
  batchCount?: number;
  /**
   * Rows retired so far across the WHOLE engine call — this batch's `rowsDone`
   * plus every earlier sub-batch of the same call (`batch 1/2`, `batch 2/2`).
   *
   * The unit the CALLER cares about: one engine call renders one contiguous run
   * of chunks, and every row that has retired inside it is a chunk whose audio
   * exists, whatever sub-batch it retired in. `rowsDone` alone resets to 0 at
   * every sub-batch boundary, so folding THAT into a chunk count would make the
   * count fall back by a whole sub-batch each time one ended.
   *
   * Optional only for the wire: an object restored from a queue.json written by
   * a build that predates this field has none. Always set by advanceBatch.
   */
  rowsRetiredInCall?: number;
  /**
   * When THIS batch's decode began (epoch ms), so a surface can say how long it
   * has been running. Set when the batch is first seen and carried unchanged
   * through its heartbeats; a new batch restarts it.
   *
   * Timed separately from the step because a batch is its own unit of work: the
   * step's elapsed folds in every batch before this one plus the model load, and
   * "13 minutes" against THIS batch is the number that says whether the decode
   * is running at its usual cadence.
   */
  startedAt?: number;
}

/** Internal carry-over between heartbeats of the same batch. */
export interface ActiveBatchState extends ActiveBatchProgress {
  /** Last decode step seen — a non-increasing step means a NEW batch started. */
  lastStep: number;
  /**
   * Rows retired by the EARLIER sub-batches of the engine call this batch belongs
   * to. 0 for the first sub-batch and for any batch whose lineage cannot be
   * proven (see advanceBatch) — a fresh call starts the count over, because its
   * rows are chunks the bridge has not yet counted anywhere.
   */
  retiredBefore: number;
  /** Identity of the batch this state describes (see batchKey). */
  key: string;
  updatedAt: number;
}

/**
 * The token-derived fraction is capped here: it is only an "elapsed against the
 * worst case" estimate, and a bar sitting at 100% while rows are still decoding
 * is the same lie as a frozen bar. Once rows retire, rowsDone/rowsTotal takes
 * over and can legitimately reach 1.
 */
const TOKEN_FRACTION_CAP = 0.95;

const HEARTBEAT_RE =
  /MLX batch generating:\s*(\d+) rows,\s*~(\d+) tokens(?:\s*\(step (\d+)(?:\/(\d+))?\))?(?:,\s*(\d+)\/(\d+) rows done)?(?:,\s*batch (\d+)\/(\d+))?/i;

/** Parse one worker stdout line. Returns null for anything that isn't a heartbeat. */
export function parseMlxHeartbeat(line: string): MlxHeartbeat | null {
  const m = line.match(HEARTBEAT_RE);
  if (!m) return null;
  const num = (s: string | undefined) => (s === undefined ? undefined : Number(s));
  return {
    rowsTotal: Number(m[1]),
    maxTokens: Number(m[2]),
    step: num(m[3]),
    tokenCap: num(m[4]),
    // m[6] is the "done" line's own total; it must agree with rowsTotal, and the
    // rows figure is taken from m[1] either way, so m[6] is only a sanity anchor.
    rowsDone: num(m[5]),
    batchNo: num(m[7]),
    batchCount: num(m[8]),
  };
}

/**
 * Identity of the batch a heartbeat belongs to. Two consecutive engine calls can
 * both print "batch 1/1" with the same width, so the key alone can't separate
 * them — the step reset does (see advanceBatch).
 */
function batchKey(hb: MlxHeartbeat): string {
  return `${hb.batchNo ?? '-'}/${hb.batchCount ?? '-'}:${hb.rowsTotal}:${hb.tokenCap ?? '-'}`;
}

/**
 * Fold a heartbeat into the running batch state.
 *
 * `prev` is the state from the previous heartbeat of the SAME worker, or
 * undefined when no batch is known to be running. A new batch is detected by a
 * changed key OR a step that did not advance (back-to-back identical batches),
 * and starts the fraction over — batches are independent units of work.
 *
 * The fraction is `max(rowsDone/rowsTotal, min(step/tokenCap, 0.95))`, then
 * clamped to never fall below the previous value within the same batch: the
 * token estimate leads early (before any row retires) and the row count takes
 * over once rows start finishing, and the changeover would otherwise step
 * backwards (32% of the token budget spent, but only 1 of 95 rows retired).
 *
 * `retiredBefore` carries ACROSS a sub-batch boundary of the same engine call,
 * and only there. One call can be split into several batches ("batch 2/3"), and
 * `rowsDone` restarts at 0 in each — so the next sub-batch inherits the rows the
 * previous ones retired, and `rowsRetiredInCall` keeps rising for the whole call.
 * The lineage test is deliberately strict (same batchCount, batchNo exactly one
 * higher): anything else is treated as a FRESH call and starts at 0, because
 * over-carrying would credit chunks twice in the count the bridge folds it into.
 * A last heartbeat that reported no `rows done` contributes its full width — the
 * batch ended, so every row in it retired.
 */
export function advanceBatch(prev: ActiveBatchState | undefined, hb: MlxHeartbeat): ActiveBatchState {
  const key = batchKey(hb);
  const step = hb.step ?? 0;
  const sameBatch = prev !== undefined && prev.key === key && step > prev.lastStep;

  const isNextSubBatch = prev !== undefined
    && !sameBatch
    && hb.batchNo !== undefined
    && prev.batchNo !== undefined
    && hb.batchCount !== undefined
    && prev.batchCount !== undefined
    && hb.batchCount === prev.batchCount
    && hb.batchNo === prev.batchNo + 1;
  const retiredBefore = sameBatch
    ? prev!.retiredBefore
    : isNextSubBatch
      ? prev!.retiredBefore + (prev!.rowsDone ?? prev!.rowsTotal)
      : 0;

  // No row count and no token cap = nothing to build a fraction out of. Say so
  // (absent) instead of publishing a zero that looks like a stalled bar.
  const hasBasis = hb.rowsDone !== undefined || (hb.tokenCap !== undefined && hb.tokenCap > 0);
  let fraction: number | undefined;
  if (hasBasis) {
    const rowsFraction = hb.rowsTotal > 0 ? (hb.rowsDone ?? 0) / hb.rowsTotal : 0;
    const tokenFraction = hb.tokenCap && hb.tokenCap > 0
      ? Math.min(step / hb.tokenCap, TOKEN_FRACTION_CAP)
      : 0;
    fraction = Math.max(rowsFraction, tokenFraction);
    if (sameBatch && prev!.fraction !== undefined) fraction = Math.max(fraction, prev!.fraction);
    fraction = Math.min(1, Math.max(0, fraction));
  }

  const now = Date.now();
  return {
    rowsTotal: hb.rowsTotal,
    rowsDone: hb.rowsDone,
    tokenStep: hb.maxTokens,
    tokenCap: hb.tokenCap,
    fraction,
    batchNo: hb.batchNo,
    batchCount: hb.batchCount,
    retiredBefore,
    rowsRetiredInCall: retiredBefore + (hb.rowsDone ?? 0),
    // Carried for the SAME batch, restarted for a new one — the same test that
    // resets the fraction, for the same reason: batches are independent units.
    startedAt: sameBatch ? prev!.startedAt ?? now : now,
    lastStep: step,
    key,
    updatedAt: now,
  };
}

/** Strip the carry-over bookkeeping before publishing to the renderer. */
export function toActiveBatchProgress(state: ActiveBatchState): ActiveBatchProgress {
  return {
    rowsTotal: state.rowsTotal,
    rowsDone: state.rowsDone,
    tokenStep: state.tokenStep,
    tokenCap: state.tokenCap,
    fraction: state.fraction,
    batchNo: state.batchNo,
    batchCount: state.batchCount,
    rowsRetiredInCall: state.rowsRetiredInCall,
    startedAt: state.startedAt,
  };
}
