/**
 * WHERE A PERIOD DOES NOT END A SENTENCE — the align splitter's copy of the
 * guard narrator's renderer has always had.
 *
 * Owen, 2026-09-10, on a VTT generated by the alignment pass: *"alignment split
 * on abbreviations. like R.L. Dabney was split across sentences, but thats a
 * persons name. it should be complete sentences split at punctuation"*.
 *
 * There are TWO sentence splitters in this pipeline and they are not the same
 * code. `python/narrator/text/paragraph_packer.split_sentences` cuts the book
 * into render chunks; `electron/whisperx-align-bridge.splitSentences` cuts it
 * into alignment sentences. The Python one has carried an abbreviation guard
 * since the port and gained a digit rule on 2026-09-09 (`Col. 2:1`); the
 * TypeScript one had NEITHER, so `R.L. Dabney`, `Mr. Darcy` and `St. Louis` each
 * became two cues in every aligned transcript.
 *
 * ── THE THREE RULES, in the order they matter ───────────────────────────────
 *
 * 1. AN INITIAL IS NOT A TERMINATOR. A period after a LONE LETTER — `R.`, the
 *    `L.` in `R.L.`, the `S.` in `U.S.` — is part of a name. This is a SHAPE
 *    rule, not a list, and it is the one that fixes Owen's case: no set of
 *    abbreviations can enumerate people's initials.
 * 2. THE ABBREVIATION SET below, matched CASE-SENSITIVELY, so `Ch.` guards `Ch.`
 *    and not `much.`.
 * 3. NEVER BEFORE A DIGIT. The align splitter gets this free: its boundary
 *    already requires a capital or an opening quote after the space, so `No. 1`
 *    and `Col. 2:1` cannot split there. It is stated here because the Python
 *    builder spells it out (`\.(?!\s+\d)`) and a reader comparing the two should
 *    not conclude this one is missing it.
 *
 * ── WHAT IT COSTS, and why merging is the right way to be wrong here ────────
 *
 * Every one of these rules merges cues that should have split: `...she got an
 * A. Then she left.` and `...he left the U.S. Then he...` each become one cue.
 * That is the deliberate trade, and for ALIGNMENT it is much cheaper than the
 * alternative: a merged cue is one longer cue whose words are all still in it,
 * while a split name produces a fragment cue ("R.L.") that the coverage gate
 * then reports as a chunk it could not place. Same trade the renderer accepted
 * for `Mr. Darcy`.
 *
 * ── A DELIBERATE SECOND COPY, pinned by a test ──────────────────────────────
 *
 * These stems are `abbreviations_mapping['eng']` union `SENTENCE_ABBREVIATIONS`
 * from `python/narrator/text/lang.py`, reduced by that file's own stem rule
 * (drop the trailing dot, keep the last dot-segment, discard anything under two
 * characters). TypeScript cannot import Python, so
 * `tools/test-sentence-abbreviations.js` READS THE PYTHON and fails when the two
 * drift — which makes lang.py the one place a new abbreviation is added, exactly
 * as it was before this file existed.
 */

/**
 * Abbreviation STEMS — no trailing dot, because the dot is the terminator being
 * guarded. Case-sensitive. Sorted, so a diff against the Python is readable.
 */
export const SENTENCE_ABBREVIATION_STEMS: readonly string[] = [
  'Adm', 'Apr', 'Aug', 'Ave', 'Blvd', 'Capt', 'Ch', 'Chap', 'Chron', 'Co',
  'Col', 'Cor', 'Corp', 'Dan', 'Dec', 'Dept', 'Deut', 'Dr', 'Eccl', 'Ed',
  'Eds', 'Eph', 'Esq', 'Esth', 'Ex', 'Exod', 'Ezek', 'Feb', 'Fig', 'Figs',
  'Fr', 'Fri', 'Gal', 'Gen', 'Gov', 'Hab', 'Hag', 'Heb', 'Hon', 'Hos',
  'Inc', 'Isa', 'Jan', 'Jas', 'Jer', 'Jn', 'Josh', 'Jr', 'Judg', 'Jul',
  'Jun', 'Kgs', 'Lam', 'Lev', 'Lk', 'Lt', 'Ltd', 'Maj', 'Mal', 'Mar',
  'Matt', 'Mic', 'Mk', 'Mon', 'Mr', 'Mrs', 'Msgr', 'Mt', 'Nah', 'Neh',
  'Nov', 'Num', 'Obad', 'Oct', 'Pet', 'Phil', 'Philem', 'Pres', 'Prof', 'Prov',
  'Ps', 'Pss', 'Rd', 'Rep', 'Rev', 'Rom', 'Sam', 'Sat', 'Sec', 'Sen',
  'Sep', 'Sept', 'Sgt', 'Sr', 'St', 'Sun', 'Thess', 'Thu', 'Thur', 'Thurs',
  'Tim', 'Tit', 'Trans', 'Tue', 'Tues', 'Univ', 'Vol', 'Vols', 'Wed', 'Zech',
  'Zeph', 'approx', 'cf', 'et al', 'etc', 'viz', 'vs',
];

/** Regex-escape a stem. Only `.` and space occur today; this is not a place to
 *  discover that the hard way. */
function escapeRe(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * The lookbehind chain that must precede a literal `.` for it to count as a
 * sentence terminator: rule 1 then rule 2, in one string.
 *
 * Built rather than written out so the stems above are the only thing to edit,
 * and so the initials rule cannot be dropped by someone tidying the list.
 */
export function periodTerminatorGuard(): string {
  // RULE 1. `\b[A-Za-z]` is a word-boundary-preceded LONE letter: it matches the
  // `R` of `R.`, the `L` of `R.L.` (the dot before it is a boundary) and the `S`
  // of `U.S.`, and does NOT match the final letter of a longer word.
  const initials = '(?<!\\b[A-Za-z])';
  // RULE 2.
  const abbreviations = SENTENCE_ABBREVIATION_STEMS
    .map((stem) => `(?<!\\b${escapeRe(stem)})`)
    .join('');
  return initials + abbreviations;
}
